demand_data:
  url: "https://www.neso.energy/document/321056/download"
  raw: "data_sources/raw/demand_highlights.xlsx"
  cleaned: "data_sources/raw/demand_highlights_cleaned.csv"
  expanded: "data_sources/processed/demand_timeseries.csv"
  year: 2013

# For endpoint, deafult target year.
default_year: 2030